name: 'Environment: SBX'

on:
  workflow_dispatch:

env:
  location: WestEurope
  resourceGroupName: DemoResourceGroup
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  job_deploy_environment:
    runs-on: ubuntu-20.04
    name: 'Deploy environment'
    strategy:
      fail-fast: false
      matrix:
        parameterFilePaths: ['parameters.json']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Setup agent'
        shell: pwsh
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE '.github' 'scripts' 'Set-EnvironmentOnAgent.ps1')

          # Set agent up
          Set-EnvironmentOnAgent
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: 'Validate template deployment for [${{ env.resourceGroupName }}]'
        shell: pwsh
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE '.github' 'scripts' 'Test-TemplateWithParameterFile.ps1')

          # ----------- #
          # INVOKE TEST #
          # ----------- #
          $functionInput = @{
            templateFilePath   = Join-Path $env:GITHUB_WORKSPACE 'CARML' '${{ env.resourceGroupName }}' 'deploy.bicep'
            parameterFilePath  = Join-Path $env:GITHUB_WORKSPACE 'CARML' '${{ env.resourceGroupName }}' 'parameters' '${{ matrix.parameterFilePaths }}'
            location           = '${{ env.location }}'
            resourceGroupName  = '${{ env.resourceGroupName }}'
            subscriptionId     = '${{ secrets.ARM_SUBSCRIPTION_ID }}'
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Test-TemplateWithParameterFile @functionInput -Verbose
      - name: 'Deploy template [${{ env.resourceGroupName }}]'
        shell: pwsh
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourceDeployment' 'New-ModuleDeployment.ps1')

          $functionInput = @{
            templateFilePath   = Join-Path $env:GITHUB_WORKSPACE 'CARML' '${{ env.resourceGroupName }}' 'deploy.bicep'
            parameterFilePath  = Join-Path $env:GITHUB_WORKSPACE 'CARML' '${{ env.resourceGroupName }}' 'parameters' '${{ matrix.parameterFilePaths }}'
            location           = '${{ env.location }}'
            resourceGroupName  = '${{ env.resourceGroupName }}'
            subscriptionId     = '${{ secrets.ARM_SUBSCRIPTION_ID }}'
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          # Invoke deployment
          New-ModuleDeployment @functionInput -Verbose

